-- MySQL Script generated by MySQL Workbench
-- Thu May 11 08:44:01 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema vitalcert
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema vitalcert
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `vitalcert` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema new_schema1
-- -----------------------------------------------------
USE `vitalcert` ;

-- -----------------------------------------------------
-- Table `vitalcert`.`gender`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gender` ;

CREATE TABLE IF NOT EXISTS `gender` (
                                                    `gender_id` INT NOT NULL,
                                                    `gender` VARCHAR(6) NOT NULL,
                                                    PRIMARY KEY (`gender_id`),
                                                    UNIQUE INDEX `gender_UNIQUE` (`gender` ASC) VISIBLE) ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vitalcert`.`nationality`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `vitalcert`.`nationality` ;

CREATE TABLE IF NOT EXISTS `vitalcert`.`nationality` (
                                                         `nationality_id` INT NOT NULL,
                                                         `nationality` VARCHAR(100) NOT NULL,
                                                         PRIMARY KEY (`nationality_id`),
                                                         UNIQUE INDEX `nationality_UNIQUE` (`nationality` ASC) VISIBLE)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vitalcert`.`religion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `vitalcert`.`religion` ;

CREATE TABLE IF NOT EXISTS `vitalcert`.`religion` (
                                                      `religion_id` INT NOT NULL,
                                                      `religion` VARCHAR(100) NOT NULL,
                                                      PRIMARY KEY (`religion_id`),
                                                      UNIQUE INDEX `religion_UNIQUE` (`religion` ASC) VISIBLE)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vitalcert`.`social_status`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `vitalcert`.`social_status` ;

CREATE TABLE IF NOT EXISTS `vitalcert`.`social_status` (
                                                           `social_status_id` INT NOT NULL,
                                                           `social_status` VARCHAR(8) NOT NULL,
                                                           PRIMARY KEY (`social_status_id`),
                                                           UNIQUE INDEX `social_status_UNIQUE` (`social_status` ASC) VISIBLE)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vitalcert`.`military_condition`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `vitalcert`.`military_condition` ;

CREATE TABLE IF NOT EXISTS `vitalcert`.`military_condition` (
                                                                `military_condition_id` INT NOT NULL,
                                                                `military_condition` VARCHAR(20) NULL,
                                                                PRIMARY KEY (`military_condition_id`),
                                                                UNIQUE INDEX `military_condition_UNIQUE` (`military_condition` ASC) VISIBLE)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vitalcert`.`Citizen`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `vitalcert`.`Citizen` ;

CREATE TABLE IF NOT EXISTS `vitalcert`.`Citizen` (
                                                     `ssn` VARCHAR(14) NOT NULL,
                                                     `frist_name` VARCHAR(100) NOT NULL,
                                                     `middel_name` VARCHAR(100) NOT NULL,
                                                     `last_name` VARCHAR(100) NOT NULL,
                                                     `birth_date` DATE NOT NULL,
                                                     `place_of_birth` VARCHAR(100) NOT NULL,
                                                     `address` VARCHAR(100) NULL,
                                                     `father_ssn` VARCHAR(14) NULL,
                                                     `mother_ssn` VARCHAR(14) NULL,
                                                     `fingerprint` BLOB NULL,
                                                     `password` VARCHAR(100) NOT NULL,
                                                     `gender_id` INT NOT NULL,
                                                     `nationality_id` INT NOT NULL,
                                                     `religion_id` INT NOT NULL,
                                                     `social_status_id` INT NOT NULL,
                                                     `military_condition_id` INT NOT NULL,
                                                     PRIMARY KEY (`ssn`),
                                                     INDEX `fk_Citizen_gender_idx` (`gender_id` ASC) VISIBLE,
                                                     INDEX `fk_Citizen_citizenf_idx` (`father_ssn` ASC) VISIBLE,
                                                     INDEX `fk_Citizen_citizenm_idx` (`mother_ssn` ASC) VISIBLE,
                                                     INDEX `fk_Citizen_nationality1_idx` (`nationality_id` ASC) VISIBLE,
                                                     INDEX `fk_Citizen_religion1_idx` (`religion_id` ASC) VISIBLE,
                                                     INDEX `fk_Citizen_social_status1_idx` (`social_status_id` ASC) VISIBLE,
                                                     INDEX `fk_Citizen_military_condition1_idx` (`military_condition_id` ASC) VISIBLE,
                                                     CONSTRAINT `fk_Citizen_gender`
                                                         FOREIGN KEY (`gender_id`)
                                                             REFERENCES `vitalcert`.`gender` (`gender_id`)
                                                             ON DELETE NO ACTION
                                                             ON UPDATE NO ACTION,
                                                     CONSTRAINT `fk_Citizen_citizenf`
                                                         FOREIGN KEY (`father_ssn`)
                                                             REFERENCES `vitalcert`.`Citizen` (`ssn`)
                                                             ON DELETE NO ACTION
                                                             ON UPDATE NO ACTION,
                                                     CONSTRAINT `fk_Citizen_citizenm`
                                                         FOREIGN KEY (`mother_ssn`)
                                                             REFERENCES `vitalcert`.`Citizen` (`ssn`)
                                                             ON DELETE NO ACTION
                                                             ON UPDATE NO ACTION,
                                                     CONSTRAINT `fk_Citizen_nationality1`
                                                         FOREIGN KEY (`nationality_id`)
                                                             REFERENCES `vitalcert`.`nationality` (`nationality_id`)
                                                             ON DELETE NO ACTION
                                                             ON UPDATE NO ACTION,
                                                     CONSTRAINT `fk_Citizen_religion1`
                                                         FOREIGN KEY (`religion_id`)
                                                             REFERENCES `vitalcert`.`religion` (`religion_id`)
                                                             ON DELETE NO ACTION
                                                             ON UPDATE NO ACTION,
                                                     CONSTRAINT `fk_Citizen_social_status1`
                                                         FOREIGN KEY (`social_status_id`)
                                                             REFERENCES `vitalcert`.`social_status` (`social_status_id`)
                                                             ON DELETE NO ACTION
                                                             ON UPDATE NO ACTION,
                                                     CONSTRAINT `fk_Citizen_military_condition1`
                                                         FOREIGN KEY (`military_condition_id`)
                                                             REFERENCES `vitalcert`.`military_condition` (`military_condition_id`)
                                                             ON DELETE NO ACTION
                                                             ON UPDATE NO ACTION)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vitalcert`.`phone_number`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `vitalcert`.`phone_number` ;

CREATE TABLE IF NOT EXISTS `vitalcert`.`phone_number` (
                                                          `phone_number` VARCHAR(11) NOT NULL,
                                                          `ssn` VARCHAR(14) NOT NULL,
                                                          PRIMARY KEY (`phone_number`, `ssn`),
                                                          INDEX `fk_phone_number_Citizen1_idx` (`ssn` ASC) VISIBLE,
                                                          CONSTRAINT `fk_phone_number_Citizen1`
                                                              FOREIGN KEY (`ssn`)
                                                                  REFERENCES `vitalcert`.`Citizen` (`ssn`)
                                                                  ON DELETE NO ACTION
                                                                  ON UPDATE NO ACTION)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vitalcert`.`office`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `vitalcert`.`office` ;

CREATE TABLE IF NOT EXISTS `vitalcert`.`office` (
                                                    `office_number` INT NOT NULL,
                                                    `address` VARCHAR(100) NOT NULL,
                                                    PRIMARY KEY (`office_number`))
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vitalcert`.`office_phone`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `vitalcert`.`office_phone` ;

CREATE TABLE IF NOT EXISTS `vitalcert`.`office_phone` (
                                                          `phone` VARCHAR(11) NOT NULL,
                                                          `office_number` INT NOT NULL,
                                                          PRIMARY KEY (`phone`, `office_number`),
                                                          INDEX `fk_office_phone_office1_idx` (`office_number` ASC) VISIBLE,
                                                          CONSTRAINT `fk_office_phone_office1`
                                                              FOREIGN KEY (`office_number`)
                                                                  REFERENCES `vitalcert`.`office` (`office_number`)
                                                                  ON DELETE NO ACTION
                                                                  ON UPDATE NO ACTION)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vitalcert`.`employee_account`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `vitalcert`.`employee_account` ;

CREATE TABLE IF NOT EXISTS `vitalcert`.`employee_account` (
                                                              `employee_id` INT NOT NULL,
                                                              `password` VARCHAR(100) NOT NULL,
                                                              `ssn` VARCHAR(14) NOT NULL,
                                                              PRIMARY KEY (`employee_id`),
                                                              INDEX `fk_employee_account_Citizen1_idx` (`ssn` ASC) VISIBLE,
                                                              CONSTRAINT `fk_employee_account_Citizen1`
                                                                  FOREIGN KEY (`ssn`)
                                                                      REFERENCES `vitalcert`.`Citizen` (`ssn`)
                                                                      ON DELETE NO ACTION
                                                                      ON UPDATE NO ACTION)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vitalcert`.`request_state`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `vitalcert`.`request_state` ;

CREATE TABLE IF NOT EXISTS `vitalcert`.`request_state` (
                                                           `request_state_id` INT NOT NULL,
                                                           `request_state` VARCHAR(8) NOT NULL,
                                                           PRIMARY KEY (`request_state_id`),
                                                           UNIQUE INDEX `request_state_UNIQUE` (`request_state` ASC) VISIBLE)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vitalcert`.`cirteficate`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `vitalcert`.`cirteficate` ;

CREATE TABLE IF NOT EXISTS `vitalcert`.`cirteficate` (
                                                         `certificate_number` INT NOT NULL,
                                                         `type` VARCHAR(100) NOT NULL,
                                                         PRIMARY KEY (`certificate_number`, `type`))
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vitalcert`.`requests`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `vitalcert`.`requests` ;

CREATE TABLE IF NOT EXISTS `vitalcert`.`requests` (
                                                      `request_id` INT NOT NULL,
                                                      `request_date` DATE NOT NULL,
                                                      `request_state_id` INT NOT NULL,
                                                      `certificate_number` INT NOT NULL,
                                                      `cirteficate_type` VARCHAR(100) NOT NULL,
                                                      `ssn` VARCHAR(14) NOT NULL,
                                                      PRIMARY KEY (`request_id`),
                                                      INDEX `fk_requests_request_state1_idx` (`request_state_id` ASC) VISIBLE,
                                                      INDEX `fk_requests_cirteficate1_idx` (`certificate_number` ASC, `cirteficate_type` ASC) VISIBLE,
                                                      INDEX `fk_requests_Citizen1_idx` (`ssn` ASC) VISIBLE,
                                                      CONSTRAINT `fk_requests_request_state1`
                                                          FOREIGN KEY (`request_state_id`)
                                                              REFERENCES `vitalcert`.`request_state` (`request_state_id`)
                                                              ON DELETE NO ACTION
                                                              ON UPDATE NO ACTION,
                                                      CONSTRAINT `fk_requests_cirteficate1`
                                                          FOREIGN KEY (`certificate_number` , `cirteficate_type`)
                                                              REFERENCES `vitalcert`.`cirteficate` (`certificate_number` , `type`)
                                                              ON DELETE NO ACTION
                                                              ON UPDATE NO ACTION,
                                                      CONSTRAINT `fk_requests_Citizen1`
                                                          FOREIGN KEY (`ssn`)
                                                              REFERENCES `vitalcert`.`Citizen` (`ssn`)
                                                              ON DELETE NO ACTION
                                                              ON UPDATE NO ACTION)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vitalcert`.`price`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `vitalcert`.`price` ;

CREATE TABLE IF NOT EXISTS `vitalcert`.`price` (
                                                   `price_id` INT NOT NULL,
                                                   `pricec` DOUBLE NOT NULL,
                                                   `pricing_date` DATE NOT NULL,
                                                   `cirteficate_certificate_number` INT NOT NULL,
                                                   `cirteficate_type` VARCHAR(100) NOT NULL,
                                                   PRIMARY KEY (`price_id`),
                                                   INDEX `fk_price_cirteficate1_idx` (`cirteficate_certificate_number` ASC, `cirteficate_type` ASC) VISIBLE,
                                                   CONSTRAINT `fk_price_cirteficate1`
                                                       FOREIGN KEY (`cirteficate_certificate_number` , `cirteficate_type`)
                                                           REFERENCES `vitalcert`.`cirteficate` (`certificate_number` , `type`)
                                                           ON DELETE NO ACTION
                                                           ON UPDATE NO ACTION)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vitalcert`.`invoice`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `vitalcert`.`invoice` ;

CREATE TABLE IF NOT EXISTS `vitalcert`.`invoice` (
                                                     `invoice_id` INT NOT NULL,
                                                     `price_id` INT NOT NULL,
                                                     `certificate_number` INT NOT NULL,
                                                     `type` VARCHAR(100) NOT NULL,
                                                     `ssn` VARCHAR(14) NOT NULL,
                                                     `number_of_copies` INT NOT NULL,
                                                     PRIMARY KEY (`invoice_id`),
                                                     INDEX `fk_invoice_price1_idx` (`price_id` ASC) VISIBLE,
                                                     INDEX `fk_invoice_cirteficate1_idx` (`certificate_number` ASC, `type` ASC) VISIBLE,
                                                     INDEX `fk_invoice_Citizen1_idx` (`ssn` ASC) VISIBLE,
                                                     CONSTRAINT `fk_invoice_price1`
                                                         FOREIGN KEY (`price_id`)
                                                             REFERENCES `vitalcert`.`price` (`price_id`)
                                                             ON DELETE NO ACTION
                                                             ON UPDATE NO ACTION,
                                                     CONSTRAINT `fk_invoice_cirteficate1`
                                                         FOREIGN KEY (`certificate_number` , `type`)
                                                             REFERENCES `vitalcert`.`cirteficate` (`certificate_number` , `type`)
                                                             ON DELETE NO ACTION
                                                             ON UPDATE NO ACTION,
                                                     CONSTRAINT `fk_invoice_Citizen1`
                                                         FOREIGN KEY (`ssn`)
                                                             REFERENCES `vitalcert`.`Citizen` (`ssn`)
                                                             ON DELETE NO ACTION
                                                             ON UPDATE NO ACTION)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vitalcert`.`criminal_record`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `vitalcert`.`criminal_record` ;

CREATE TABLE IF NOT EXISTS `vitalcert`.`criminal_record` (
                                                             `certificate_number` INT NOT NULL,
                                                             `type` VARCHAR(100) NOT NULL,
                                                             `embployee_ssn` VARCHAR(14) NOT NULL,
                                                             `Citizen_ssn` VARCHAR(14) NOT NULL,
                                                             `citizen_picture` BLOB NOT NULL,
                                                             `produced_to` VARCHAR(100) NOT NULL,
                                                             `result` VARCHAR(100) NOT NULL,
                                                             `office_number` INT NOT NULL,
                                                             INDEX `fk_criminal_record_cirteficate1_idx` (`certificate_number` ASC, `type` ASC) VISIBLE,
                                                             INDEX `fk_criminal_record_Citizen1_idx` (`embployee_ssn` ASC) VISIBLE,
                                                             INDEX `fk_criminal_record_Citizen2_idx` (`Citizen_ssn` ASC) VISIBLE,
                                                             PRIMARY KEY (`certificate_number`),
                                                             INDEX `fk_criminal_record_office1_idx` (`office_number` ASC) VISIBLE,
                                                             CONSTRAINT `fk_criminal_record_cirteficate1`
                                                                 FOREIGN KEY (`certificate_number` , `type`)
                                                                     REFERENCES `vitalcert`.`cirteficate` (`certificate_number` , `type`)
                                                                     ON DELETE NO ACTION
                                                                     ON UPDATE NO ACTION,
                                                             CONSTRAINT `fk_criminal_record_Citizen1`
                                                                 FOREIGN KEY (`embployee_ssn`)
                                                                     REFERENCES `vitalcert`.`Citizen` (`ssn`)
                                                                     ON DELETE NO ACTION
                                                                     ON UPDATE NO ACTION,
                                                             CONSTRAINT `fk_criminal_record_Citizen2`
                                                                 FOREIGN KEY (`Citizen_ssn`)
                                                                     REFERENCES `vitalcert`.`Citizen` (`ssn`)
                                                                     ON DELETE NO ACTION
                                                                     ON UPDATE NO ACTION,
                                                             CONSTRAINT `fk_criminal_record_office1`
                                                                 FOREIGN KEY (`office_number`)
                                                                     REFERENCES `vitalcert`.`office` (`office_number`)
                                                                     ON DELETE NO ACTION
                                                                     ON UPDATE NO ACTION)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vitalcert`.`marriage`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `vitalcert`.`marriage` ;

CREATE TABLE IF NOT EXISTS `vitalcert`.`marriage` (
                                                      `certificate_number` INT NOT NULL,
                                                      `wife_ssn` VARCHAR(14) NOT NULL,
                                                      `husband_ssn` VARCHAR(14) NOT NULL,
                                                      `office_number` INT NOT NULL,
                                                      `registration_date` DATE NOT NULL,
                                                      `marriage_date` DATE NOT NULL,
                                                      `place_of_marriage` VARCHAR(100) NOT NULL,
                                                      PRIMARY KEY (`certificate_number`),
                                                      INDEX `fk_marriage_Citizen1_idx` (`wife_ssn` ASC) VISIBLE,
                                                      INDEX `fk_marriage_Citizen2_idx` (`husband_ssn` ASC) VISIBLE,
                                                      INDEX `fk_marriage_office1_idx` (`office_number` ASC) VISIBLE,
                                                      CONSTRAINT `fk_marriage_cirteficate1`
                                                          FOREIGN KEY (`certificate_number`)
                                                              REFERENCES `vitalcert`.`cirteficate` (`certificate_number`)
                                                              ON DELETE NO ACTION
                                                              ON UPDATE NO ACTION,
                                                      CONSTRAINT `fk_marriage_Citizen1`
                                                          FOREIGN KEY (`wife_ssn`)
                                                              REFERENCES `vitalcert`.`Citizen` (`ssn`)
                                                              ON DELETE NO ACTION
                                                              ON UPDATE NO ACTION,
                                                      CONSTRAINT `fk_marriage_Citizen2`
                                                          FOREIGN KEY (`husband_ssn`)
                                                              REFERENCES `vitalcert`.`Citizen` (`ssn`)
                                                              ON DELETE NO ACTION
                                                              ON UPDATE NO ACTION,
                                                      CONSTRAINT `fk_marriage_office1`
                                                          FOREIGN KEY (`office_number`)
                                                              REFERENCES `vitalcert`.`office` (`office_number`)
                                                              ON DELETE NO ACTION
                                                              ON UPDATE NO ACTION)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vitalcert`.`divorce_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `vitalcert`.`divorce_type` ;

CREATE TABLE IF NOT EXISTS `vitalcert`.`divorce_type` (
                                                          `divorce_type_id` INT NOT NULL,
                                                          `divorce_type` VARCHAR(30) NOT NULL,
                                                          PRIMARY KEY (`divorce_type_id`),
                                                          UNIQUE INDEX `divorce_type_UNIQUE` (`divorce_type` ASC) VISIBLE)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vitalcert`.`divorce`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `vitalcert`.`divorce` ;

CREATE TABLE IF NOT EXISTS `vitalcert`.`divorce` (
                                                     `office_number` INT NOT NULL,
                                                     `certificate_number` INT NOT NULL,
                                                     `type` VARCHAR(100) NOT NULL,
                                                     `wife_ssn` VARCHAR(14) NOT NULL,
                                                     `husband_ssn` VARCHAR(14) NOT NULL,
                                                     `divorce_date` DATE NOT NULL,
                                                     `registration_date` DATE NOT NULL,
                                                     `authority` VARCHAR(100) NOT NULL,
                                                     `divorce_type_id` INT NOT NULL,
                                                     INDEX `fk_divorce_office1_idx` (`office_number` ASC) VISIBLE,
                                                     INDEX `fk_divorce_cirteficate1_idx` (`certificate_number` ASC, `type` ASC) VISIBLE,
                                                     PRIMARY KEY (`certificate_number`),
                                                     INDEX `fk_divorce_Citizen1_idx` (`wife_ssn` ASC) VISIBLE,
                                                     INDEX `fk_divorce_Citizen2_idx` (`husband_ssn` ASC) VISIBLE,
                                                     INDEX `fk_divorce_divorce_type1_idx` (`divorce_type_id` ASC) VISIBLE,
                                                     CONSTRAINT `fk_divorce_office1`
                                                         FOREIGN KEY (`office_number`)
                                                             REFERENCES `vitalcert`.`office` (`office_number`)
                                                             ON DELETE NO ACTION
                                                             ON UPDATE NO ACTION,
                                                     CONSTRAINT `fk_divorce_cirteficate1`
                                                         FOREIGN KEY (`certificate_number` , `type`)
                                                             REFERENCES `vitalcert`.`cirteficate` (`certificate_number` , `type`)
                                                             ON DELETE NO ACTION
                                                             ON UPDATE NO ACTION,
                                                     CONSTRAINT `fk_divorce_Citizen1`
                                                         FOREIGN KEY (`wife_ssn`)
                                                             REFERENCES `vitalcert`.`Citizen` (`ssn`)
                                                             ON DELETE NO ACTION
                                                             ON UPDATE NO ACTION,
                                                     CONSTRAINT `fk_divorce_Citizen2`
                                                         FOREIGN KEY (`husband_ssn`)
                                                             REFERENCES `vitalcert`.`Citizen` (`ssn`)
                                                             ON DELETE NO ACTION
                                                             ON UPDATE NO ACTION,
                                                     CONSTRAINT `fk_divorce_divorce_type1`
                                                         FOREIGN KEY (`divorce_type_id`)
                                                             REFERENCES `vitalcert`.`divorce_type` (`divorce_type_id`)
                                                             ON DELETE NO ACTION
                                                             ON UPDATE NO ACTION)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vitalcert`.`governorate`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `vitalcert`.`governorate` ;

CREATE TABLE IF NOT EXISTS `vitalcert`.`governorate` (
                                                         `governorate_id` INT NOT NULL,
                                                         `governorate_name` VARCHAR(100) NOT NULL,
                                                         PRIMARY KEY (`governorate_id`),
                                                         UNIQUE INDEX `governorate_name_UNIQUE` (`governorate_name` ASC) VISIBLE)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vitalcert`.`health_center`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `vitalcert`.`health_center` ;

CREATE TABLE IF NOT EXISTS `vitalcert`.`health_center` (
                                                           ` health_center_id` INT NOT NULL,
                                                           `health_center_name` VARCHAR(100) NOT NULL,
                                                           `health_center_address` VARCHAR(100) NULL,
                                                           `governorate_id` INT NOT NULL,
                                                           PRIMARY KEY (` health_center_id`),
                                                           INDEX `fk_health_center_governorate1_idx` (`governorate_id` ASC) VISIBLE,
                                                           CONSTRAINT `fk_health_center_governorate1`
                                                               FOREIGN KEY (`governorate_id`)
                                                                   REFERENCES `vitalcert`.`governorate` (`governorate_id`)
                                                                   ON DELETE NO ACTION
                                                                   ON UPDATE NO ACTION)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vitalcert`.`dearh`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `vitalcert`.`dearh` ;

CREATE TABLE IF NOT EXISTS `vitalcert`.`dearh` (
                                                   `health_center_id` INT NOT NULL,
                                                   `ssn` VARCHAR(14) NOT NULL,
                                                   `office_number` INT NOT NULL,
                                                   `certificate_number` INT NOT NULL,
                                                   `type` VARCHAR(100) NOT NULL,
                                                   `registration_date` DATE NOT NULL,
                                                   `dearh_date` DATE NOT NULL,
                                                   `reason` VARCHAR(100) NOT NULL,
                                                   `place_of_dearh` VARCHAR(100) NOT NULL,
                                                   INDEX `fk_dearh_health_center1_idx` (`health_center_id` ASC) VISIBLE,
                                                   INDEX `fk_dearh_Citizen1_idx` (`ssn` ASC) VISIBLE,
                                                   INDEX `fk_dearh_office1_idx` (`office_number` ASC) VISIBLE,
                                                   INDEX `fk_dearh_cirteficate1_idx` (`certificate_number` ASC, `type` ASC) VISIBLE,
                                                   PRIMARY KEY (`certificate_number`),
                                                   CONSTRAINT `fk_dearh_health_center1`
                                                       FOREIGN KEY (`health_center_id`)
                                                           REFERENCES `vitalcert`.`health_center` (` health_center_id`)
                                                           ON DELETE NO ACTION
                                                           ON UPDATE NO ACTION,
                                                   CONSTRAINT `fk_dearh_Citizen1`
                                                       FOREIGN KEY (`ssn`)
                                                           REFERENCES `vitalcert`.`Citizen` (`ssn`)
                                                           ON DELETE NO ACTION
                                                           ON UPDATE NO ACTION,
                                                   CONSTRAINT `fk_dearh_office1`
                                                       FOREIGN KEY (`office_number`)
                                                           REFERENCES `vitalcert`.`office` (`office_number`)
                                                           ON DELETE NO ACTION
                                                           ON UPDATE NO ACTION,
                                                   CONSTRAINT `fk_dearh_cirteficate1`
                                                       FOREIGN KEY (`certificate_number` , `type`)
                                                           REFERENCES `vitalcert`.`cirteficate` (`certificate_number` , `type`)
                                                           ON DELETE NO ACTION
                                                           ON UPDATE NO ACTION)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vitalcert`.`birth`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `vitalcert`.`birth` ;

CREATE TABLE IF NOT EXISTS `vitalcert`.`birth` (
                                                   `registration_date` INT NOT NULL,
                                                   `certificate_number` INT NOT NULL,
                                                   `type` VARCHAR(100) NOT NULL,
                                                   `ssn` VARCHAR(14) NOT NULL,
                                                   ` health_center_id` INT NOT NULL,
                                                   `office_number` INT NOT NULL,
                                                   PRIMARY KEY (`registration_date`, `certificate_number`),
                                                   INDEX `fk_birth_cirteficate1_idx` (`certificate_number` ASC, `type` ASC) VISIBLE,
                                                   INDEX `fk_birth_Citizen1_idx` (`ssn` ASC) VISIBLE,
                                                   INDEX `fk_birth_health_center1_idx` (` health_center_id` ASC) VISIBLE,
                                                   INDEX `fk_birth_office1_idx` (`office_number` ASC) VISIBLE,
                                                   CONSTRAINT `fk_birth_cirteficate1`
                                                       FOREIGN KEY (`certificate_number` , `type`)
                                                           REFERENCES `vitalcert`.`cirteficate` (`certificate_number` , `type`)
                                                           ON DELETE NO ACTION
                                                           ON UPDATE NO ACTION,
                                                   CONSTRAINT `fk_birth_Citizen1`
                                                       FOREIGN KEY (`ssn`)
                                                           REFERENCES `vitalcert`.`Citizen` (`ssn`)
                                                           ON DELETE NO ACTION
                                                           ON UPDATE NO ACTION,
                                                   CONSTRAINT `fk_birth_health_center1`
                                                       FOREIGN KEY (` health_center_id`)
                                                           REFERENCES `vitalcert`.`health_center` (` health_center_id`)
                                                           ON DELETE NO ACTION
                                                           ON UPDATE NO ACTION,
                                                   CONSTRAINT `fk_birth_office1`
                                                       FOREIGN KEY (`office_number`)
                                                           REFERENCES `vitalcert`.`office` (`office_number`)
                                                           ON DELETE NO ACTION
                                                           ON UPDATE NO ACTION)
    ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
